<?php

namespace backend\models;

use Yii;

/**
 * This is the model class for table "goods_intro".
 *
 * @property integer $goods_id
 * @property string $intro
 */
class GoodsIntro extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'goods_intro';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['intro'], 'string'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'intro' => '商品详细',
        ];
    }
    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes);
        if(!$insert){
            $this->UnlinkGoods();
        }
    }
    protected function UnlinkGoods(){
        $format='@frontend/web/html/%s.html';
        $filePath=Yii::getAlias(sprintf($format,$this->id));
        unlink($filePath);
    }
    public function afterDelete()
    {
        parent::afterDelete(); // TODO: Change the autogenerated stub
        try{
            $this->UnlinkGoods();
        }
        catch (\Exception $e){}
    }
}
